services:
  mysql:
    image: mysql:8-oracle
    restart: unless-stopped
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--socket=/tmp/mysql.sock']
    environment:
      - MYSQL_ROOT_PASSWORD=cae_root_pw
      - MYSQL_HOST=canvas_app_explorer_mysql
      - MYSQL_TCP_PORT=3306
      - MYSQL_DATABASE=canvas_app_explorer_local
      - MYSQL_USER=cae_user
      - MYSQL_PASSWORD=cae_pw
    ports:
      - "6306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:ro
    container_name: canvas_app_explorer_mysql
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
      args:
        TZ: ${TZ}
    volumes:
      # Mount only the needed directories for local development
      - ./frontend/app:/code/frontend/app
      - ./backend:/code/backend
      - ${HOME}/mylasecrets:/secrets
    ports:
      - "5000:5000"
      - "5020:5020"
    container_name: canvas_app_explorer
    env_file:
      - .env
    environment:
      - DEBUG=True
